language: node_js

node_js:
  - "5.0.0"
  - "5.1.1"

services:
  - mongodb

before_script:
  - npm install

script:
  - export NODE_ENV=staging && npm run build && npm test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js